// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CitySelect: typeof import('./components/city-select/city-select.vue')['default']
    Item: typeof import('./components/item/index.vue')['default']
    LeftSwipeTab: typeof import('./components/left-swipe-tab/left-swipe-tab.vue')['default']
    List: typeof import('./components/list/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('./components/tab/index.vue')['default']
    VearCarousel: typeof import('./components/vear-carousel/vear-carousel.vue')['default']
  }
}
